spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=redis-10560.crce217.ap-south-1-1.ec2.cloud.redislabs.com
spring.data.redis.port=10560
spring.data.redis.username=yash
spring.data.redis.password=Yash@1234


spring.cache.type=redis


#spring.cache.redis.time-to-live=600000
